export class ArticleService {
  async getArticles() {
    return articles;
  }

  turnTitleToTitleUri(title: string) {
    const encodedTitle = encodeURIComponent(title);
    return encodedTitle.toLowerCase().replace(/%20/g, "_"); // Replace spaces with underscores
  }

  turnTitleUriToTitle(title_uri: string) {
    const decodedTitle = title_uri.replace(/_/g, "%20"); // Replace underscores with spaces
    return decodeURIComponent(decodedTitle);
  }

  async getArticleByTitleUri(title_uri: string) {
    const foundArticle = articles.find((article) => {
      return (
        this.turnTitleToTitleUri(article.title).toLowerCase() ===
        title_uri.toLowerCase()
      );
    });
    console.log(foundArticle);
    return foundArticle;
  }
}

const articles: Article[] = [
  {
    id: 1,
    title: "How does Crypto-Blender.com work?",
    body: `**Crypto-Blender** is a tool that makes Ethereum (more) **anonymous**. It works pretty straightforwardly. The sender of the payment puts their money into a pool, which then "shuffles" around all the Ethereums and divides them into the recipients\'s addresses based on the amount sent.\n\n**How Crypto-Blender Works in Three Easy Steps**\n\n1. **Enter the Ethereum Address**: Start by entering the Ethereum address (or addresses) where you want to receive the mixed Ethereum. Optionally, you can set a delay for processing your transaction. Remember, the longer the delay, the higher the anonymity of the mixed Ethereum.\n\n2. **Send Your Ethereum**: Send the Ethereum you want to mix to the address generated by Crypto-Blender.\n\n3. **Wait for Confirmation**: After the first confirmation of your deposit, Crypto-Blender will initiate the mixing process for your Ethereum. Once completed, they will be sent to the address (or addresses) you provided in the first step.\nThat's it! Crypto-Blender makes it simple to enhance the privacy and security of your Ethereum transactions.`,
    uploadTime: new Date("2023-10-06T12:00:00"),
    readTime: 2,
    shortDescription:
      "Are your Ethereum transactions truly private? Discover the enigmatic power of Crypto-Blender, the mysterious tool that shrouds your Ethereum in anonymity. Dive into the shadows as it shuffles and conceals your digital assets, leaving no trace. In just three covert steps, you can cloak your Ethereum like a pro. But beware, the deeper you go, the more impenetrable your Ethereum's secrets become. Explore the clandestine world of Crypto-Blender now. Your Ethereum's anonymity is at stake.",
  },
  {
    id: 2,
    title: "But wait... isn't ethereum anonymous?",
    body: `Absolutely not — Ethereum is pseudo-anonymous. **Sending and receiving Ethereum leaves a fingerprint**. If the fingerprint is ever linked to your identity, everything you have ever "touched" will be linked to you.\n\nAll the “fingerprints” are publicly stored in Ethereum's blockchain. Therefore, **anyone you send Ethereum to can look up your previous transactions or even see your crypto balance.**`,
    uploadTime: new Date("2023-10-01T12:00:00"),
    readTime: 1,
    shortDescription:
      "Hold your Ethereum transactions under the magnifying glass - they're not as discreet as they seem. Ethereum's pseudo-anonymity can betray you, leaving a digital fingerprint that, if exposed, could unravel your entire crypto history. Dive into the revealing world of Ethereum's blockchain, where every move is laid bare. Your crypto balance and transaction history are just a click away for anyone you've ever dealt with. Don't miss the shocking truth about Ethereum's true anonymity!",
  },
  {
    id: 3,
    title: "How can a mixer make Etehereum anonymous? CoinJoin is the answer.",
    body: `**CoinJoin is a type of anonymous transaction that helps Ethereum users maintain their privacy while sending Ethereum.** CoinJoin is a multiparty "Ethereum mixing" transaction at the end of which it is unclear who owns which coin.\n\nConsider the following transactions made at the same time: A purchases an item from B, C purchases an item from D, and E purchases an item from F. Without CoinJoin, the public blockchain ledger would record three separate transactions for each input-output match.\n\nWith CoinJoin, only one single transaction is recorded. The ledger would show that Ethereums were paid from A, C, and E addresses to B, D, and F. By masking the deals made by all parties, an observer cannot with full certainty determine who sent Ethereums to whom.\n\nWhile some believe that CoinJoin is a new technology, this is not valid. CoinJoin is simply an advancement on already existing technology - Ethereum. And Ethereum mixers bring CoinJoin technology to users.`,
    uploadTime: new Date("2023-09-29T12:00:00"),
    readTime: 2,
    shortDescription:
      "Are you puzzled by how Ethereum can become truly anonymous? The answer lies in CoinJoin, the ultimate guardian of your privacy in the crypto world. CoinJoin is the art of mingling Ethereum transactions, obscuring the trail to ownership. Read more about CoinJoin",
  },
  {
    id: 4,
    title: "Why should I choose Crypto-Blender Ethereum Mixer? ",
    body: `<h2 class="text-lg uppercase font-bold">Fast Ethereum mixer</h2>The speed of a Ethereum mixer can be an important consideration for users who want to quickly and efficiently obscure the origin of their Ethereum transactions.\n\n<strong>Crypto-Blender Ethereum mixer offers an instant mixing service, which allows you to receive your mixed Ethereum within a few minutes after the first confirmation of your deposit.</strong>\n\nOptionally, to enhance the privacy of the Ethereum mixing transaction, you can choose a delay in processing your mixing request.\n\n<h2 class="text-lg uppercase font-bold">SECURE ETHEREUM MIXER</h2>The security of a Ethereum mixer can vary depending on the specific service being used. Some Ethereum mixers may have strong security measures in place to protect the privacy of their users, while others may be less secure.\n\nIt is important to carefully research any Ethereum mixer that you are considering using and to ensure that they have strong security measures in place. This can include things like secure servers, encrypted communication, and anonymous registration processes.\n\nTo guarantee the highest level of server and application security at all times, Crypto-Blender employs a team of IT and security specialists. <strong>Additionally, to increase the safety and privacy of our users, we never require or log any personal details, such as name, email, or IP address, and delete all transaction details after 24 hours.</strong>\n\n<h2 class="text-lg uppercase font-bold">CONVENIENT ETHEREUM MIXER</h2>The convenience of a Ethereum mixer can depend on a few factors, such as the user's specific needs and the features and user experience of the mixer service being used.\n\nSome users may find Ethereum mixers to be convenient because they allow them to quickly and easily obscure the origin of their Ethereum transactions. Other users may find Ethereum mixers to be inconvenient because they may have limits on the amount of Ethereum that can be mixed at one time, or because they may require users to go through additional steps to use the service.\n\n<strong>Crypto-Blender Ethereum mixer combines the speed, privacy and affordability, while allowing you to mix up to 450 ETH/WETH in a single transaction, without registration or KYC.</strong>`,
    uploadTime: new Date("2023-09-21T12:00:00"),
    readTime: 5,
    shortDescription:
      "Discover why Crypto-Blender is the ultimate choice for Ethereum mixing. With lightning-fast transactions, top-notch security, and unmatched convenience, we redefine Ethereum anonymity. Receive your mixed Ethereum within minutes, shielded by our ironclad security, and mix up to 450 ETH/WETH hassle-free. Choose Crypto-Blender for total peace of mind.",
  },
];

export interface Article {
  id: number;
  readTime: Number;
  uploadTime: Date;
  title: string;
  body: string;
  shortDescription: string;
}
